### ISSUE TITLE
Settle on how to add custom(local) css stylesheets

### ISSUE THREAD

**Issue by ICESpartan** [antonva/podypus#11]
And add to maven

**Comment by ICESpartan** [comment]
Custom stylesheets can be added locally now through using thymeleaf. As it has the capabilities to reference local objects which can be added through the html.

Example 
```<link rel="stylesheet"  href="../static/css/homeStyle.css" th:href="@{/css/homeStyle.css}"/>```


Just point href from the html to the css file as usual with html. Then add th:href and point it to the relative position of the css file in respect to the html using the above syntax.

**Comment by antonva** [comment]
Changing `spring.mvc.static-path-pattern=/static/**` in `application.properties` allows us to simply point to the `static` directory under `resources`.

Now  you can simply do `<link rel="stylesheet" href="/static/css/homeStyle.css"/>`.
Refer to the fragments branch to see this in action.
