### ISSUE TITLE
Get player to add to source enclosed links

### ISSUE THREAD

**Issue by ICESpartan** [antonva/podypus#35]
Lines 49-55 in searchControler.java are somewhat an attempt to access an episode, but due to the List implementation it seems little hared than expected. Commented out so the core code will work.

episodes.html is supposed to be a templete for the output of episodes.

The client-side functionality is nearly there on another stashed branch Im on. But depends highly on the completion of the functionality above to work.

**Comment by antonva** [comment]
Each endpoint can only take one view or fragment. If you want to nest fragments you need to create a parent fragment that includes the children. 

I added the enclosure episode listing to the searchresult fragment to illustrate how to get enclosure urls. Be aware that they can be null for whatever reason, in which case I'm falling back to the Episode "link" attribute.
